version: '3.5'

services:
  datasbase:
    image: 'postgres:14'
    container_name: 'manageshop_database_postgres_14'
    restart: 'always'
    volumes:
      - './data/db/postgres:/var/lib/postgresql'
    environment:
      - 'POSTGRES_DB=manage_shop'
      - 'POSTGRES_USER=manage_shop'
      - 'POSTGRES_PASSWORD=manage_shop'
    ports:
      - target: 5432
        published: 5454
        protocol: 'tcp'
        mode: 'host'